replicaCount: 1
image:
  repository: eberttc.azurecr.io/user-api
  tag: "latest"

specs:
  ingress:
    enabled: true
    publicUrl: api.zubale.com
    port: 4000
  service:
    name: http
    port: 4000
    protocol: TCP
    type: ClusterIP

configmap:
  owner: "eberttc"

secrets:
  project:
    key:     
  