name: CI

on:
  - push

jobs:
  linux:
    name: CI elixir
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir:
          - "1.13"
        otp:
          - "24.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore deps
        uses: actions/cache@v2
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install dependencies
        run: mix deps.get

      - name: Compile dependencies
        run: MIX_ENV=test mix deps.compile

      - name: Check code format
        run: MIX_ENV=test mix format --check-formatted

      - name: Lint code
        run: MIX_ENV=test mix credo

      - name: Run tests
        run: mix test
